#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

composer update
composer install
npm install
npm install --save-dev vite laravel-vite-plugin
npm install --save-dev @vitejs/plugin-vue
npm run dev
npm run build
php artisan migrate
chmod -R ugo+rw /.composer
chmod -R 775 storage
chmod -R 777 storage

if [ ! -z "$PORT" ]; then
    sed -i -e "s/--port=80/--port=$PORT/g" /etc/supervisor/conf.d/supervisord.conf
fi

cat .env | grep -q APP_KEY=base64
if [ ! "$?" -eq 0 ]; then
    php artisan key:generate
fi

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord
fi
